
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "host1" do |h1|
    h1.vm.network "private_network", ip: "192.168.10.2"
    h1.vm.hostname = "host1"
    h1.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/main.yml"
      ansible.inventory_path="ansible/inventory"
    end
  end

  config.vm.define "host2" do |h2|
    h2.vm.network "private_network", ip: "192.168.10.3"
    h2.vm.hostname = "host2"
    h2.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/main.yml"
      ansible.inventory_path="ansible/inventory"
    end
  end

  config.vm.define "host3" do |h3|
    h3.vm.network "private_network", ip: "192.168.10.4"
    h3.vm.hostname = "host3"
    h3.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/main.yml"
      ansible.inventory_path="ansible/inventory"
    end
  end

  config.vm.define "host4" do |h4|
    h4.vm.network "private_network", ip: "192.168.10.5"
    h4.vm.hostname = "host4"
    h4.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/main.yml"
      ansible.inventory_path="ansible/inventory"
    end
  end

  config.vm.define "host5" do |h5|
    h5.vm.network "private_network", ip: "192.168.10.6"
    h5.vm.hostname = "host5"
    h5.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "ansible/main.yml"
      ansible.inventory_path="ansible/inventory"
    end
  end

end
