
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "host1" do |h1|
    h1.vm.network "private_network", ip: "192.168.10.2"
  end

  config.vm.define "host2" do |h2|
    h2.vm.network "private_network", ip: "192.168.10.3"
  end

  config.vm.define "host3" do |h3|
    h3.vm.network "private_network", ip: "192.168.10.4"
  end

  config.vm.define "host4" do |h4|
    h4.vm.network "private_network", ip: "192.168.10.5"
  end

  config.vm.define "host5" do |h5|
    h5.vm.network "private_network", ip: "192.168.10.6"
  end
end
